### ISSUE TITLE
Nombre de congresista transgénero

### ISSUE THREAD

**Issue by jincio** [DecideBienpe/db-electoral-vue#29]
https://twitter.com/esteban_mp4/status/1353705709695860736

**Comment by aniversarioperu** [comment]
en otorongo.club usamos el nombre preferido por la candidata https://otorongo.club/2021/candidato/70250793/

**Comment by jincio** [comment]
Genial, 

Vamos a hacer ese cambio. Una consulta @aniversarioperu  conocen de otro caso para ir corrigiendo también?

**Comment by aniversarioperu** [comment]
solo conozco ese caso.
